# Generated by Django 4.2.16 on 2024-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetail',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
