# Generated by Django 4.2.16 on 2024-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0002_usersdetail_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdetail',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='usersdetail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='usersdetail',
            name='passport',
        ),
        migrations.AlterField(
            model_name='usersdetail',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='usersdetail',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
