# Generated by Django 4.2.16 on 2024-09-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0003_remove_usersdetail_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
