# Generated by Django 4.2.16 on 2024-09-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0004_alter_usersdetail_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
