# Generated by Django 5.1.2 on 2024-12-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0006_alter_usersdetail_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetail',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
