# Generated by Django 5.1.2 on 2024-12-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0008_dashboardprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
