# Generated by Django 5.1.2 on 2024-12-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0009_dashboardprofile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardProfile',
        ),
    ]
