# Generated by Django 5.1.2 on 2024-12-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0012_remove_dashboardprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardprofile',
            name='landingpage_image',
            field=models.ImageField(blank=True, null=True, upload_to='landingpage_profiles/'),
        ),
    ]
