# Generated by Django 4.2.16 on 2024-09-24 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=50)),
                ('pen_number', models.IntegerField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualBird',
            fields=[
                ('bird_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_hatch', models.DateField()),
                ('point_of_lay_date', models.DateField(blank=True, null=True)),
                ('generation', models.IntegerField()),
                ('hatch', models.CharField(max_length=100)),
                ('sire_id', models.IntegerField(blank=True, null=True)),
                ('dam_id', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.breed')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.house')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualEggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('egg_count', models.IntegerField()),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.individualbird')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupFeedWaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('female_count', models.IntegerField()),
                ('male_count', models.IntegerField()),
                ('total_bird_count', models.IntegerField()),
                ('feed_given', models.FloatField()),
                ('feed_refusal', models.FloatField(blank=True, null=True)),
                ('water_given', models.FloatField()),
                ('water_refusal', models.FloatField(blank=True, null=True)),
                ('mortality', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.breed')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.house')),
            ],
        ),
        migrations.CreateModel(
            name='GroupEggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_hatch', models.DateField()),
                ('point_of_lay_date', models.DateField(blank=True, null=True)),
                ('collection_date', models.DateField()),
                ('female_count', models.IntegerField()),
                ('male_count', models.IntegerField()),
                ('total_bird_count', models.IntegerField()),
                ('morning_egg_production', models.IntegerField()),
                ('afternoon_egg_production', models.IntegerField()),
                ('total_egg_production', models.IntegerField()),
                ('mortality', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.breed')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.house')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBodyWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_hatch', models.DateField()),
                ('point_of_lay_date', models.DateField(blank=True, null=True)),
                ('record_date', models.DateField()),
                ('age_in_weeks', models.IntegerField()),
                ('female_count', models.IntegerField()),
                ('male_count', models.IntegerField()),
                ('total_bird_count', models.IntegerField()),
                ('total_birds_weighed', models.IntegerField()),
                ('total_weight', models.FloatField()),
                ('mortality', models.IntegerField()),
                ('culling', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.breed')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.house')),
            ],
        ),
    ]
