# Generated by Django 4.2.16 on 2024-09-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0002_rename_breed_name_breed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='pen_number',
            field=models.CharField(max_length=50),
        ),
    ]
