# Generated by Django 4.2.16 on 2024-09-25 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poultry', '0003_alter_breed_id_alter_house_id_alter_house_pen_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualFeedWaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('feed_given', models.FloatField()),
                ('feed_refusal', models.FloatField(blank=True, null=True)),
                ('water_given', models.FloatField()),
                ('water_refusal', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.individualbird')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualBodyWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('weight', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.individualbird')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
