# Generated by Django 4.2.16 on 2024-09-26 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poultry', '0006_remove_groupbodyweight_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickengroup',
            name='collector',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
