# Generated by Django 4.2.16 on 2024-09-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0007_chickengroup_collector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupbodyweight',
            old_name='total_birds_weighed',
            new_name='total_birds_weighted',
        ),
    ]
