# Generated by Django 5.1.2 on 2024-11-01 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0008_rename_total_birds_weighed_groupbodyweight_total_birds_weighted'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCulling',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('male_count', models.IntegerField(default=0)),
                ('female_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField()),
                ('chicken_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.chickengroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDeath',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('male_count', models.IntegerField(default=0)),
                ('female_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField()),
                ('chicken_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.chickengroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupReplacement',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('male_count', models.IntegerField(default=0)),
                ('female_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField()),
                ('chicken_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.chickengroup')),
            ],
        ),
    ]
