# Generated by Django 5.1.2 on 2024-11-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0010_groupculling_collector_groupdeath_collector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupfeedwaterintake',
            name='water_given',
        ),
        migrations.RemoveField(
            model_name='groupfeedwaterintake',
            name='water_refusal',
        ),
        migrations.RemoveField(
            model_name='individualfeedwaterintake',
            name='water_given',
        ),
        migrations.RemoveField(
            model_name='individualfeedwaterintake',
            name='water_refusal',
        ),
        migrations.AlterField(
            model_name='groupdeath',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
