# Generated by Django 5.1.2 on 2024-11-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0011_remove_groupfeedwaterintake_water_given_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupbodyweight',
            name='mortality',
        ),
        migrations.RemoveField(
            model_name='groupeggproduction',
            name='mortality',
        ),
        migrations.RemoveField(
            model_name='groupfeedwaterintake',
            name='mortality',
        ),
    ]
