# Generated by Django 5.1.2 on 2024-11-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0012_remove_groupbodyweight_mortality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupbodyweight',
            name='culling',
        ),
    ]
