# Generated by Django 5.1.2 on 2024-11-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0013_remove_groupbodyweight_culling'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualbird',
            name='condition',
            field=models.CharField(default='alive', max_length=100),
        ),
    ]
