# Generated by Django 5.1.2 on 2024-11-01 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0014_individualbird_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualbird',
            name='condition',
        ),
        migrations.CreateModel(
            name='IndividualDeath',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('condition', models.IntegerField(default='alive', max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.individualbird')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
