# Generated by Django 5.1.2 on 2024-11-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0015_remove_individualbird_condition_individualdeath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualdeath',
            name='condition',
            field=models.CharField(default='alive', max_length=200),
        ),
    ]
