# Generated by Django 5.1.2 on 2024-11-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0016_alter_individualdeath_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualbird',
            name='dam_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='individualbird',
            name='sire_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
