# Generated by Django 5.1.2 on 2024-11-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0017_alter_individualbird_dam_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualbird',
            old_name='bird_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='individualbird',
            name='chicken_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
