# Generated by Django 5.1.2 on 2024-11-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0018_rename_bird_id_individualbird_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualbird',
            old_name='chicken_id',
            new_name='bird_id',
        ),
    ]
