# Generated by Django 5.1.2 on 2024-11-02 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0019_rename_chicken_id_individualbird_bird_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupVaccination',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('disease_type', models.CharField(blank=True, max_length=255, null=True)),
                ('vaccine_type', models.CharField(blank=True, max_length=255, null=True)),
                ('vaccine_method', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('chicken_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.chickengroup')),
                ('collector', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
