# Generated by Django 5.1.2 on 2024-11-02 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0023_hatcheryrecord_collector_hatcherysummary_collector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatcheryrecord',
            name='breed_of_chicken',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poultry.breed'),
        ),
    ]
