# Generated by Django 5.1.2 on 2024-11-02 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0025_alter_hatcheryrecord_collector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatcheryrecord',
            name='breed_of_chicken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.breed'),
        ),
        migrations.AlterField(
            model_name='hatcheryrecord',
            name='collector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
