# Generated by Django 5.1.2 on 2024-11-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0026_alter_hatcheryrecord_breed_of_chicken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatcherysummary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
