# Generated by Django 5.1.2 on 2024-11-03 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0027_hatcherysummary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatcherysummary',
            name='chicken_breed',
        ),
        migrations.AddField(
            model_name='hatcherysummary',
            name='breed_of_chicken',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poultry.breed'),
        ),
    ]
