# Generated by Django 5.1.2 on 2024-11-28 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0028_remove_hatcherysummary_chicken_breed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenDistribution',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('distribution_id', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_hatch', models.DateField()),
                ('recipient_name', models.CharField(help_text='Name of the recipient', max_length=200)),
                ('requester', models.CharField(help_text='Place where the recipient is located', max_length=200)),
                ('recipient_phone_number', models.CharField(help_text='Phone number of the recipient', max_length=15)),
                ('male_users_count', models.PositiveIntegerField(default=0, help_text='Number of male buyers')),
                ('female_users_count', models.PositiveIntegerField(default=0, help_text='Number of female buyers')),
                ('healthy_hatchlings_count', models.PositiveIntegerField(default=0, help_text='Number of healthy hatchlings')),
                ('number_of_eggs_incubated', models.PositiveIntegerField(default=0, help_text='Number of eggs incubated before hatching')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.breed')),
                ('distributor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
