# Generated by Django 5.1.2 on 2024-11-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0029_chickendistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('requester_id', models.CharField(blank=True, max_length=200, null=True)),
                ('requester_name', models.CharField(help_text='Name of the recipient', max_length=200)),
                ('requester_region', models.CharField(max_length=200)),
                ('requester_district', models.CharField(max_length=200)),
                ('requester_city', models.CharField(max_length=200)),
                ('requester_phone_number', models.CharField(max_length=15)),
                ('requester_male_count', models.PositiveIntegerField(default=0)),
                ('requester_female_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='chickendistribution',
            old_name='distribution_id',
            new_name='chicken_distribution_id',
        ),
        migrations.RemoveField(
            model_name='chickendistribution',
            name='female_users_count',
        ),
        migrations.RemoveField(
            model_name='chickendistribution',
            name='male_users_count',
        ),
        migrations.RemoveField(
            model_name='chickendistribution',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='chickendistribution',
            name='recipient_phone_number',
        ),
        migrations.AlterField(
            model_name='chickendistribution',
            name='healthy_hatchlings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chickendistribution',
            name='number_of_eggs_incubated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chickendistribution',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.requester'),
        ),
    ]
